version: 0.1.{build}

image:
  - Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

install:
  - cmd: powershell Install-Product node 12 x64
  - cmd: appveyor DownloadFile http://developer.download.nvidia.com/compute/cuda/11.0.2/local_installers/cuda_11.0.2_451.48_win10.exe -FileName cuda.exe
  - cmd: cuda.exe -s
  - cmd: set PATH=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin;%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v11.0\libnvvp;%PATH%
  - cmd: set "CUDA_PATH=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v11.0"
  - git reset --hard HEAD
  - yarn
  - yarn global add pkg node-gyp
  - node --version

build_script:
  - npm run build
