version: 0.1.{build}

image:
  - Ubuntu

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

install:
  - sh: nvm install 12
  - sh: wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin
  - sh: sudo mv cuda-ubuntu1804.pin /etc/apt/preferences.d/cuda-repository-pin-600
  - sh: wget http://developer.download.nvidia.com/compute/cuda/11.0.2/local_installers/cuda-repo-ubuntu1804-11-0-local_11.0.2-450.51.05-1_amd64.deb
  - sh: sudo dpkg -i cuda-repo-ubuntu1804-11-0-local_11.0.2-450.51.05-1_amd64.deb
  - sh: sudo apt-key add /var/cuda-repo-ubuntu1804-11-0-local/7fa2af80.pub
  - sh: sudo apt-get update
  - sh: sudo apt-get -y install cuda
  - sh: export CUDA_PATH=/usr/local/cuda-11.0
  - sh: export PATH=/usr/local/cuda-11.0/bin${PATH:+:${PATH}}
  - sh: export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/cuda-11.0/lib64
  - sh: export PATH=/usr/local/cuda-11.0/bin${PATH:+:${PATH}}
  - git reset --hard HEAD
  - yarn
  - yarn global add pkg node-gyp
  - node --version

build_script:
  - npm run build

artifacts:
  - path: ./nq-miner.zip
    name: nq-miner
